<?php

namespace Epar\ServiceBundle\Entity;

/**
 * EbayProfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EbayProfilesRepository extends \Doctrine\ORM\EntityRepository
{
}
